# Generated by Django 5.2.7 on 2025-10-21 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='student',
            name='residence',
            field=models.CharField(choices=[('Boarding', 'Boarding'), ('Day', 'Day')], default='Boarding', max_length=10),
        ),
    ]
